import 'questions.dart';
import 'dart:math';


class QuizBrain {
  static List<Questions> _questionBank = [
    Questions(q: 'The currency of Japan is the yen.', a: true),
    Questions(q: 'The Eiffel Tower is located in Berlin.', a: false),
    Questions(q: 'The human brain weighs approximately 5 pounds.', a: false),
    Questions(q: 'A triangle has four sides.', a: false),
    Questions(
        q: 'The Great Barrier Reef is off the coast of Australia.', a: true),
    Questions(q: 'Goldfish have a three-second memory.', a: false),
    Questions(
        q: 'The Declaration of Independence was signed in 1776.', a: true),
    Questions(q: 'The largest planet in the solar system is Saturn.', a: false),
    Questions(q: 'The capital of Brazil is Rio de Janeiro.', a: false),
    Questions(
        q: 'The Sahara Desert is the largest desert in the world.', a: true),
    Questions(q: 'The capital of France is \'London\'.', a: false),
    Questions(q: 'The Earth is flat.', a: false),
    Questions(q: 'The Nile River is the longest river in the world.', a: true),
    Questions(q: 'Mount Everest is the highest mountain on Earth.', a: true),
    Questions(q: 'The chemical symbol for gold is \'Gd\'.', a: false),
    Questions(q: 'The Great Wall of China can be seen from space.', a: false),
    Questions(q: 'The human body has 206 bones.', a: true),
    Questions(q: 'Water boils at 100 degrees Celsius at sea level.', a: true),
    Questions(q: 'The largest planet in our solar system is \'Mars\'.', a: false),
    Questions(q: 'The Mona Lisa was painted by \'Leonardo da Vinci\'.', a: true),
    Questions(q: 'The Atlantic Ocean is the largest ocean on Earth.', a: false),
    Questions(q: 'Cats are mammals.', a: true),
    Questions(q: 'The currency of Japan is the yen.', a: true),
    Questions(q: 'The Eiffel Tower is located in Berlin.', a: false),
    Questions(q: 'The human brain weighs approximately 5 pounds.', a: false),
    Questions(q: 'A triangle has four sides.', a: false),
    Questions(q: 'The Great Barrier Reef is off the coast of Australia.', a: true),
    Questions(q: 'Goldfish have a three-second memory.', a: false),
    Questions(q: 'The Declaration of Independence was signed in 1776.', a: true),
    Questions(q: 'The largest planet in the solar system is Saturn.', a: false),
    Questions(q: 'The capital of Brazil is Rio de Janeiro.', a: false),
    Questions(q: 'The Sahara Desert is the largest desert in the world.', a: true),
    Questions(q: 'The sun is a star.', a: true),
    Questions(q: 'The chemical symbol for oxygen is O2.', a: false),
    Questions(q: 'Bananas grow on trees.', a: false),
    Questions(q: 'The speed of sound is faster in water than in air.', a: true),
    Questions(q: 'A marathon is a race that is 10 miles long.', a: false),
    Questions(q: 'Venus is the hottest planet in our solar system.', a: true),
    Questions(q: 'The Statue of Liberty was a gift from France to the USA.', a: true),
    Questions(q: 'A right angle measures 90 degrees.', a: true),
    Questions(q: 'Octopuses have three hearts.', a: true),
    Questions(q: 'The currency of India is the rupee.', a: true),
    Questions(q: 'The Pacific Ocean is the deepest ocean on Earth.', a: true),
    Questions(q: 'The moon has its own atmosphere.', a: false),
    Questions(q: 'Dolphins are fish.', a: false),
    Questions(q: 'The first human to walk on the moon was Neil Armstrong.', a: true),
    Questions(q: 'Albert Einstein developed the theory of relativity.', a: true),
    Questions(q: 'The Earth orbits the sun.', a: true),
    Questions(q: 'A hexagon has five sides.', a: false),
    Questions(q: 'The Leaning Tower of Pisa is in Italy.', a: true),
    Questions(q: 'The Amazon River is the longest river in the world.', a: true),
    Questions(q: 'The chemical symbol for silver is \'Ag\'.', a: true),
    Questions(q: 'Kangaroos are native to Africa.', a: false),
    Questions(q: 'The human skeleton is made up of 206 bones.', a: true),
    Questions(q: 'The capital of Australia is Sydney.', a: false),
    Questions(q: 'The Taj Mahal is located in India.', a: true),
    Questions(q: 'The currency of Canada is the euro.', a: false),
    Questions(q: 'The Nile River flows through Egypt.', a: true),
    Questions(q: 'The United States has 50 states.', a: true),
    Questions(q: 'The currency of Russia is the ruble.', a: true),
    Questions(q: 'The Statue of Liberty was a gift from France to the United States.', a: true),
    Questions(q: 'The Colosseum is located in Athens.', a: false),
    Questions(q: 'The highest-grossing film of all time is "Avatar."', a: true),
    Questions(q: 'The planet closest to the sun is Venus.', a: false),
    Questions(q: 'The moon has its own gravitational force.', a: true),
    Questions(q: 'A decagon has ten sides.', a: true),
    Questions(q: 'A mammal is a type of reptile.', a: false),
    Questions(q: 'Water boils at 100 degrees Celsius (212 degrees Fahrenheit) at sea level.', a: true),
    Questions(q: 'The chemical symbol for gold is Au.', a: true),
    Questions(q: 'The Earth\'s equator is a line of longitude.', a: false),
    Questions(q: 'A hexagon has eight sides.', a: false),
    Questions(q: 'The largest planet in our solar system is Saturn.', a: false),
    Questions(q: 'The human body has 206 bones.', a: true),
    Questions(q: 'The largest organ in the human body is the skin.', a: true),
    Questions(q: 'A centimeter is larger than a millimeter.', a: true),
    Questions(q: 'The chemical symbol for oxygen is O2.', a: false),
    Questions(q: 'A right triangle has an angle of 90 degrees.', a: true),
    Questions(q: 'The prime meridian passes through Greenwich, England.', a: true),
    Questions(q: 'The human heart has four chambers.', a: true),
    Questions(q: 'The Pacific Ocean is the largest ocean on Earth.', a: true),
    Questions(q: 'A square has six sides.', a: false),
    Questions(q: 'The chemical symbol for carbon is C.', a: true),
    Questions(q: 'The Earth revolves around the moon.', a: false),
    Questions(q: 'The Celsius and Fahrenheit scales have the same freezing point.', a: false),
    Questions(q: 'The human body has 12 pairs of cranial nerves.', a: false),
    Questions(q: 'A rhinoceros is a type of reptile.', a: false),
    Questions(q: 'The Great Barrier Reef is located in the Caribbean.', a: false),
    Questions(q: 'The Amazon Rainforest is mainly located in South America.', a: true),
    Questions(q: 'A kilogram is a unit of volume.', a: false),
    Questions(q: 'The chemical symbol for hydrogen is H.', a: true),
    Questions(q: 'The Earth\'s core is primarily composed of iron and nickel.', a: true),
        Questions(q: 'A right angle measures 180 degrees.', a: false),
    Questions(q: 'A heptagon has seven sides.', a: true),
    Questions(q: 'The highest mountain in Africa is Mount Kilimanjaro.', a: true),
    Questions(q: 'The human body has 32 permanent teeth.', a: false),
    Questions(q: 'The chemical symbol for silver is Si.', a: false),
    Questions(q: 'The Sahara Desert is located in Africa.', a: true),
    Questions(q: 'A triangle has four sides.', a: false),
    Questions(q: 'All angles in a rectangle are right angles.', a: true),
    Questions(q: 'A circle has three sides.', a: false),
    Questions(q: 'A square is a type of parallelogram.', a: true),
    Questions(q: 'A right triangle has an angle of 90 degrees.', a: true),
    Questions(q: 'The sum of the angles in a triangle is always 180 degrees.', a: true),
    Questions(q: 'A hexagon has six sides.', a: true),
    Questions(q: 'A rhombus has all sides of equal length.', a: false),
    Questions(q: 'A polygon with eight sides is called an octagon.', a: true),
    Questions(q: 'The diameter of a circle is twice the length of its radius.', a: true),
    Questions(q: 'William the Conqueror was the first Norman king of England.', a: true),
    Questions(q: 'The Magna Carta was signed by King Henry VIII.', a: false),
    Questions(q: 'The English Civil War took place in the 17th century.', a: true),
    Questions(q: 'The Black Death was a devastating plague that struck England in the 15th century.', a: false),
    Questions(q: 'Queen Elizabeth I was the daughter of King Henry VIII.', a: true),
    Questions(q: 'The Battle of Hastings in 1066 resulted in the Norman conquest of England.', a: true),
    Questions(q: 'The War of the Roses was a conflict between the House of Lancaster and the House of York.', a: true),
    Questions(q: 'The Industrial Revolution began in England in the 18th century.', a: true),
    Questions(q: 'King Richard the Lionheart ruled England during the 13th century.', a: true),
    Questions(q: 'The English Reformation was initiated by King Henry VIII.', a: true),
    Questions(q: 'Queen Victoria was the longest-reigning British monarch.', a: true),
    Questions(q: 'The Great Fire of London occurred in the 16th century.', a: false),
    Questions(q: 'The English Bill of Rights was passed in the 17th century.', a: true),
    Questions(q: 'The Battle of Agincourt was a significant English victory in the Hundred Years\' War.', a: true),
    Questions(q: 'Oliver Cromwell served as Lord Protector of the Commonwealth of England.', a: true),
    Questions(q: 'The Magna Carta limited the power of the monarchy and established certain legal rights.', a: true),
    Questions(q: 'The English monarchy was abolished during the Glorious Revolution.', a: false),
    Questions(q: 'The Norman kings of England spoke Old English.', a: false),
    Questions(q: 'The Elizabethan Era is known for its flourishing of arts and literature.', a: true),
    Questions(q: 'The Battle of Trafalgar was a naval battle between England and France.', a: true),
    Questions(q: 'Gravity is a force that causes objects to repel each other.', a: false),
    Questions(q: 'Newton\'s First Law of Motion states that an object in motion tends to stay in motion unless acted upon by an external force.', a: true),
    Questions(q: 'The speed of light is approximately 300,000 kilometers per second in a vacuum.', a: true),
    Questions(q: 'A calorie is a unit of measurement for temperature.', a: false),
    Questions(q: 'Momentum is the product of an object\'s mass and its acceleration.', a: true),
    Questions(q: 'The Earth orbits the Sun in a perfectly circular path.', a: false),
    Questions(q: 'In physics, "work" is defined as the amount of effort or energy exerted on an object.', a: true),
    Questions(q: 'Sound travels faster in a vacuum than in air.', a: false),
    Questions(q: 'The nucleus of an atom is typically made up of protons and neutrons.', a: true),
    Questions(q: 'An object at rest has no energy.', a: false),
    Questions(q: 'A convex lens always converges light rays.', a: true),
    Questions(q: 'The law of conservation of energy states that energy can be created or destroyed in any process.', a: false),
    Questions(q: 'In a vacuum, all objects fall at the same rate regardless of their mass.', a: true),
    Questions(q: 'The unit of electrical resistance is the ohm.', a: true),
    Questions(q: 'The theory of relativity was developed by Sir Isaac Newton.', a: false),
      ];
  int _qNum = Random().nextInt(_questionBank.length);

 String getQuestionText() {
   return _questionBank[_qNum].questionText;
 }

  bool getQuestionAnswer() {
    return _questionBank[_qNum].questionAnswer;
  }

  void nextQuestion() {
   _qNum = Random().nextInt(_questionBank.length);
   }

}
//Learning: Underscore makes object private to this class